name: PHP CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: PHP CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php }}

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix src/

      - name: Apply PHP CS Fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'PHP CS Fixer: Apply automated code style changes.'

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon
