name: PHP CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: PHP CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.18.0
        with:
          php-version: "8.0.0"
          tools: php-cs-fixer, pocketmine/pocketmine-mp

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix src/

      - name: Apply automated changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Apply automated code style changes.'
