name: PHP CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run PHPStan
        uses: larryTheCoder/pmmp-phpstan-action@master
        with:
          phpstan-config: phpstan.neon.dist

  codestyle:
    name: Code Style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          tools: php-cs-fixer

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix src

      - name: Apply php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CodeStyle: Apply fix changes'
